# Generated by Django 5.0.14 on 2026-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='village',
            name='unique_village_name_per_company',
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('company', 'name'), name='unique_active_village_name_per_company'),
        ),
    ]
