# Generated by Django 5.0.14 on 2026-09-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_phone', models.CharField(blank=True, max_length=20)),
                ('bags', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_method', models.CharField(choices=[('weighed', 'Pesé'), ('estimated', 'Estimé')], max_length=10)),
                ('standard_bag_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_per_bag', models.PositiveIntegerField(help_text='GNF, entier')),
                ('amount', models.PositiveIntegerField(help_text='GNF, calculé par le serveur')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy_m', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('gps_exemption_reason', models.CharField(blank=True, max_length=255)),
                ('quality', models.CharField(blank=True, choices=[('good', 'Bonne'), ('medium', 'Moyenne'), ('low', 'Faible')], max_length=10)),
                ('moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé')], default='active', max_length=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('needs_review', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('clock_skew_flagged', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.company')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounts.village')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('cancel', 'Annulation'), ('conflict', 'Conflit')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchases.purchase')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'purchase history',
                'db_table': 'purchase_history',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sequences', to='accounts.company')),
            ],
            options={
                'db_table': 'purchase_sequences',
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('op_id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('entity_id', models.UUIDField()),
                ('status', models.CharField(choices=[('applied', 'Appliquée'), ('conflict', 'Conflit'), ('rejected', 'Rejetée')], max_length=10)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('result', models.JSONField(help_text='Snapshot renvoyé au premier traitement, rejoué tel quel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operations',
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'purchased_at'], name='purchases_company_58174a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'village'], name='purchases_company_c6e5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['collector', 'updated_at'], name='purchases_collect_9d4280_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasesequence',
            constraint=models.UniqueConstraint(fields=('company', 'year'), name='unique_sequence_per_company_year'),
        ),
    ]
